import { Metadata } from "next";
import NavMenu from "./NavMenu";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fireship Clone",
  description: "Generated by Freddy :)",

  icons: {
    icon: '/logo.svg'
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" scroll-smooth">
      <body
        style={{
          backgroundImage:
            "linear-gradient(to bottom, #13181c, #14191f, #151a22, #161b25, #191c28);",
          minHeight: "100vh",
        }}
      >
        <NavMenu />
        <main>{children}</main>
      </body>
    </html>
  );
}
